spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
weather:
  key: 0BrSxbFIjeUMQLGppLn%2BwppOaUE62kikn%2BXHx1LJsWy%2FhwRXvBtU04si9RcPAm85eGFKUrYXlPAa0mUtCnHYkg%3D%3D
  key2: 629f45cbcec5cd5b0a1855b63d015b7d

app:
  dir:
    uploadimgdir: imgs/
    uploadaudiodir: audios/
